server:
  port: 8811
spring:
  application:
    name: consumer-demo
  zipkin:
    base-url: http://127.0.0.1:9411
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
feign:
  hystrix:
    enabled: true