server:
  port: 8809
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: provider-storage-service
  zipkin:
    base-url: http://127.0.0.1:9411
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_storage?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group